-- アプリケーションパッケージを使用
USE APPLICATION PACKAGE {{package_name}};
USE SCHEMA PUBLIC;

-- スキーマに対する使用権限を付与
GRANT REFERENCE_USAGE ON DATABASE PODB_WEATHER TO SHARE IN APPLICATION PACKAGE {{package_name}};

CREATE OR REPLACE TABLE PUBLIC.DAILY_AMEDAS (
    OBSERVATORY_NAME VARCHAR,
    DATE DATE,
    RAINFALL_DAILY_TOTAL FLOAT,
    TEMPERATURE_DAILY_AVG FLOAT,
    TEMPERATURE_DAILY_MAX FLOAT,
    TEMPERATURE_DAILY_MIN FLOAT,
    WIND_SPEED_DAILY_AVG FLOAT,
    SUNLIGHT_HOURS_DAILY_TOTAL FLOAT,
    HUMIDITY_DAILY_AVG INT,
    SNOWFALL_DAILY_TOTAL INT
)
AS
SELECT 
    CONCAT(OBSERVATORY_NAME, ' (', PREF_NAME, ')') AS OBSERVATORY_NAME,
    DATE,
    RAINFALL,
    AIR_TEMPERATURE,
    AIR_TEMPERATURE_MAX,
    AIR_TEMPERATURE_MIN,
    WIND_SPEED,
    SUNLIGHT_HOURS,
    HUMIDITY,
    SNOWFALL
FROM
PREPPER_OPEN_DATA_BANK__JAPANESE_WEATHER_DATA.E_PODB.E_WT_MD;

CREATE OR REPLACE TABLE PUBLIC.DAILY_OBSERVATORY_RAINFALL (
    PREF_NAME VARCHAR,
    CITY_NAME VARCHAR,
    STREET_NAME VARCHAR,
    NEAREST_OBSERVATORY VARCHAR,
    ADDRESS_NAME VARCHAR
)
AS
SELECT * 
FROM 
PODB_WEATHER.PUBLIC.DAILY_OBSERVATORY_RAINFALL;

GRANT USAGE ON SCHEMA PUBLIC TO SHARE IN APPLICATION PACKAGE {{package_name}};
GRANT SELECT ON TABLE PUBLIC.DAILY_AMEDAS TO SHARE IN APPLICATION PACKAGE {{package_name}};
GRANT SELECT ON TABLE PUBLIC.DAILY_OBSERVATORY_RAINFALL TO SHARE IN APPLICATION PACKAGE {{package_name}};