# CI環境用の設定ファイル
# ユーザ名とぱすわーどは環境変数から取得する

default_connection_name = "production"
[connections.production]
account = "ACCOUNT_NAME"
role = "ROLE_NAME"
database = "DATABASE_NAME"
schema = "SCHEMA_NAME"
warehouse = "WAREHOUSE_NAME"
