# CI環境用の設定ファイル
# ユーザ名とぱすわーどは環境変数から取得する

[connections.dev]
account = "hqb14845"
role = "app_dev"
warehouse = "dev_xs"
user = "github_actions"

[connections.stg]
account = "rgb21417"
role = "app_dev"
warehouse = "dev_xs"
user = "github_actions"
